name=VictronBLE
version=0.4.1
author=Scott Penrose
maintainer=Scott Penrose <scottp@dd.com.au>
sentence=ESP32 library for reading Victron Energy device data via BLE for any ESP32
paragraph=Read data from Victron SmartSolar, SmartShunt, BMV, inverters and other devices using Bluetooth Low Energy advertisements. Supports multiple devices simultaneously with no pairing required.
category=Communication
url=https://gitea.sh3d.com.au/Sh3d/VictronBLE
architectures=esp32
depends=
includes=VictronBLE.h
